### PR TITLE
Installation images.

### PR DESCRIPTION
**Pull request by bartdc**

### CODE REVIEW

**Comment by WouterSioen** [comment]
thanks!

**Comment by bartdc** [comment]
Images are broken. I changed from jpg to png. I will do another PR. 

 http://www.fork-cms.com/community/documentation/detail/installation/index

**Comment by WouterSioen** [comment]
hmm, nicely noticed.

**Comment by bartdc** [comment]
JPG to PNG.

https://github.com/bartdc/documentation/commit/1aec079b4f9ef91aef1a495cad04fa48328a5d08

**Comment by WouterSioen** [comment]
@bartdc can you pr it?

**Comment by bartdc** [comment]
Simple forgot it. Done.

**Pull request merged**
